### ISSUE TITLE
Train/Dev/Test splits

### ISSUE THREAD

**Issue by dhecloud** [alecervi/switchboard-coherence-corpus#1]
Hi! Thank you for releasing the switchboard coherence dataset. Would It possible to upload the exact Train/Dev/Test splits you used for evaluating in your [paper](https://arxiv.org/pdf/2006.10157.pdf)?

**Comment by alecervi** [comment]
Hi, Thanks for your interest in our work! In our paper we use the entire Switchboard Coherence corpus as testset, and thus do not have yet an official split in Train/Dev/Test specifically for the Switchboard Coherence corpus. The data in the Swicthboard Coherence corpus was generated using the Switchboard dialogue ids in the [testset](https://github.com/alecervi/Coherence-models-for-dialogue/tree/master/data) of our previous work. Our models in the paper are trained using response selection with context + response pairs automatically generated using the dialogue ids in the [training](https://github.com/alecervi/Coherence-models-for-dialogue/tree/master/data) set of our previous work. We will release the code of our experiments soon at this [link](https://github.com/alecervi/turn-coherence-rating).

**Comment by dhecloud** [comment]
Great! Thank you very much for your clarification
